Test/post setup
Chenxi96/court-share pull request #10
Opened 2024-05-18 17:49 UTC by Chenxi96

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests. (If tests are not applicable, explain why in the next section.)
- [ ] Is there only 1 commit.

## Describe your changes
I added these files to these changes:
1. client.ts - used to interact with the database
2. singleton.ts - Enable access to the objects and methods available on Prisma Client. It then resets the mocked instance before each test is run.
3. functions-without-context.ts -  This will call the mock implementation.
4. __tests__/with-singleton.ts - This creates test that checks if user and post objects.
## Issue ticket number and link

2024-05-18 17:56 UTC, Chenxi96 commented on __tests__/page.test.jsx
> +test('should create new user ', async () => {
I added a test for User to see if when created would return the User object.

2024-05-18 17:56 UTC, Chenxi96 commented on __tests__/page.test.jsx
> +test('should fail if user does not accept terms', async () => {
I added a test if it's a empty object it will return Error

2024-05-18 17:57 UTC, Chenxi96 commented on __tests__/page.test.jsx
> +  const post = {
I added test to check if it returns post object

2024-05-23 12:16 UTC, alvinc21 requested changes

2024-05-23 12:16 UTC, alvinc21 commented on pages/p/[id].test.jsx
> +  it('render post name', async() => {
This title to the test seems inaccurate since you're testing for the owner's name.

2024-05-23 12:16 UTC, alvinc21 commented on pages/p/[id].test.jsx
> +      console.log(result.props)
Remove this, these console logs in most cases should only be used for debugging locally.

2024-05-23 12:16 UTC, alvinc21 commented on pages/p/[id].test.jsx
> +  it('fail if props is access wrong', async () => {
This title is grammatically incorrect

2024-05-23 12:16 UTC, alvinc21 commented on pages/p/[id].test.jsx
> +      }).toThrow("Cannot read properties of undefined (reading 'owner')")
This tests for what the props contain manually and does not reflect the behavior of the page. What should be done instead is to pass in malformed/empty props and test for the behaviour that takes place on the page.

2024-05-23 12:16 UTC, alvinc21 commented on components/Post.tsx
> +const Post: React.FC<{ post: PostProps }> = ( {post} ) => {
are these changes caused by linting?

2024-05-25 15:00 UTC, Chenxi96 commented on pages/index.tsx
> +  const feed = await prisma.post.findMany({
rename to `posts` instead of `feed`

2024-05-25 15:00 UTC, Chenxi96 commented on pages/index.tsx
> +  console.log(feed)
remove all console.logs

2024-05-30 00:43 UTC, alvinc21 commented
I don't have access to view the Vercel deployment failure. Why did it fail?

2024-05-31 01:50 UTC, Chenxi96 commented on __tests__/[id].test.jsx
@alvinc21 I got this to work, I noticed that when I removed the [id].test.tsx since that's the major change I did and ran npm run build it which then it worked. I started looking at each testing dependency to see if they are incompatible. I didn't find anything. I went to nextJs and looked at the jest testing section. I noticed that they put the test file inside __test__, it seems like there's a reason why they do that. After some digging I got this from stack overflow https://stackoverflow.com/questions/70832134/is-it-possible-to-put-test-files-under-pages-directory-in-next-js . let me know what you think.

2024-05-31 12:20 UTC, alvinc21 commented on __tests__/[id].test.jsx
Good find 👍 Can you put this under a similar folder structure? i.e `__tests__/pages/p/[id].test.jsx`

2024-06-02 00:15 UTC, Chenxi96 commented on __tests__/[id].test.jsx
yeah, it can be put into a similar structure 👍

2024-06-03 12:43 UTC, alvinc21 approved these changes

2024-06-03 13:39 UTC, merged